In [1]:
from torchvision import transforms

D:\Anaconda3\envs\py37\lib\site-packages\torchvision\io\image.py:13: UserWarning: Failed to load image Python extension: 
  warn(f"Failed to load image Python extension: {e}")


python的用法 --》 tensor数据类型
通过transforms.Totensor看两个问题
- transfroms该如何使用（python）
- 为什么要使用tensor数据类型

In [4]:
from PIL import Image
# Totensor将PIL Image或者numpy.array数据转换为tensor
img_path = r"D:\PycharmProjects\xiaotudui_pytorch_tutorial\dataset\train\ants_image\0013035.jpg"
img = Image.open(img_path)
print(img)

<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=768x512 at 0x19FF3ABB188>


# transfroms该如何使用（python）

In [5]:
tensor_trans = transforms.ToTensor()
# 创建一个Totensor实例化类
tensor_img = tensor_trans(img)
print(tensor_img)

tensor([[[0.3137, 0.3137, 0.3137,  ..., 0.3176, 0.3098, 0.2980],
         [0.3176, 0.3176, 0.3176,  ..., 0.3176, 0.3098, 0.2980],
         [0.3216, 0.3216, 0.3216,  ..., 0.3137, 0.3098, 0.3020],
         ...,
         [0.3412, 0.3412, 0.3373,  ..., 0.1725, 0.3725, 0.3529],
         [0.3412, 0.3412, 0.3373,  ..., 0.3294, 0.3529, 0.3294],
         [0.3412, 0.3412, 0.3373,  ..., 0.3098, 0.3059, 0.3294]],

        [[0.5922, 0.5922, 0.5922,  ..., 0.5961, 0.5882, 0.5765],
         [0.5961, 0.5961, 0.5961,  ..., 0.5961, 0.5882, 0.5765],
         [0.6000, 0.6000, 0.6000,  ..., 0.5922, 0.5882, 0.5804],
         ...,
         [0.6275, 0.6275, 0.6235,  ..., 0.3608, 0.6196, 0.6157],
         [0.6275, 0.6275, 0.6235,  ..., 0.5765, 0.6275, 0.5961],
         [0.6275, 0.6275, 0.6235,  ..., 0.6275, 0.6235, 0.6314]],

        [[0.9137, 0.9137, 0.9137,  ..., 0.9176, 0.9098, 0.8980],
         [0.9176, 0.9176, 0.9176,  ..., 0.9176, 0.9098, 0.8980],
         [0.9216, 0.9216, 0.9216,  ..., 0.9137, 0.9098, 0.

# 为什么要使用tensor数据类型

In [ ]:
# tensor数据类型包含反向传播，梯度等理论参数属性

# np.arrary转tensor

In [6]:
import cv2
cv_img = cv2.imread(img_path)

In [7]:
from torch.utils.tensorboard import SummaryWriter

In [8]:
writer = SummaryWriter("logs")
writer.add_image("Tensor_img", tensor_img)
writer.close()

# 归一化Normalize

In [9]:
# Normalize
# input-mean/std
trans_norm = transforms.Normalize([0.5,0.5,0.5], [0.5,0.5,0.5])
img_norm = trans_norm(tensor_img)
print(img_norm)

tensor([[[-0.3725, -0.3725, -0.3725,  ..., -0.3647, -0.3804, -0.4039],
         [-0.3647, -0.3647, -0.3647,  ..., -0.3647, -0.3804, -0.4039],
         [-0.3569, -0.3569, -0.3569,  ..., -0.3725, -0.3804, -0.3961],
         ...,
         [-0.3176, -0.3176, -0.3255,  ..., -0.6549, -0.2549, -0.2941],
         [-0.3176, -0.3176, -0.3255,  ..., -0.3412, -0.2941, -0.3412],
         [-0.3176, -0.3176, -0.3255,  ..., -0.3804, -0.3882, -0.3412]],

        [[ 0.1843,  0.1843,  0.1843,  ...,  0.1922,  0.1765,  0.1529],
         [ 0.1922,  0.1922,  0.1922,  ...,  0.1922,  0.1765,  0.1529],
         [ 0.2000,  0.2000,  0.2000,  ...,  0.1843,  0.1765,  0.1608],
         ...,
         [ 0.2549,  0.2549,  0.2471,  ..., -0.2784,  0.2392,  0.2314],
         [ 0.2549,  0.2549,  0.2471,  ...,  0.1529,  0.2549,  0.1922],
         [ 0.2549,  0.2549,  0.2471,  ...,  0.2549,  0.2471,  0.2627]],

        [[ 0.8275,  0.8275,  0.8275,  ...,  0.8353,  0.8196,  0.7961],
         [ 0.8353,  0.8353,  0.8353,  ...,  0

In [10]:
print(tensor_img[0][0][0])
print(img_norm[0][0][0])

tensor(0.3137)
tensor(-0.3725)


# Resize使用

In [12]:
print(img.size)
trans_resize = transforms.Resize((512,512))
img_resize = trans_resize(img)
img_resize = tensor_trans(img_resize)
print(img_resize)

(768, 512)
tensor([[[0.3137, 0.3137, 0.3176,  ..., 0.3137, 0.3137, 0.3020],
         [0.3176, 0.3176, 0.3176,  ..., 0.3098, 0.3137, 0.3020],
         [0.3216, 0.3216, 0.3176,  ..., 0.3059, 0.3137, 0.3059],
         ...,
         [0.3412, 0.3373, 0.3373,  ..., 0.0196, 0.2196, 0.3608],
         [0.3412, 0.3373, 0.3373,  ..., 0.3490, 0.3373, 0.3373],
         [0.3412, 0.3373, 0.3373,  ..., 0.3529, 0.3137, 0.3216]],

        [[0.5922, 0.5922, 0.5961,  ..., 0.5922, 0.5922, 0.5804],
         [0.5961, 0.5961, 0.5961,  ..., 0.5882, 0.5922, 0.5804],
         [0.6000, 0.6000, 0.5961,  ..., 0.5843, 0.5922, 0.5843],
         ...,
         [0.6275, 0.6235, 0.6235,  ..., 0.1020, 0.4157, 0.6157],
         [0.6275, 0.6235, 0.6235,  ..., 0.5373, 0.5882, 0.6078],
         [0.6275, 0.6235, 0.6235,  ..., 0.6392, 0.6275, 0.6275]],

        [[0.9137, 0.9137, 0.9176,  ..., 0.9137, 0.9137, 0.9020],
         [0.9176, 0.9176, 0.9176,  ..., 0.9098, 0.9137, 0.9020],
         [0.9216, 0.9216, 0.9176,  ..., 0.9059,

In [15]:
writer = SummaryWriter(r"D:\PycharmProjects\xiaotudui_pytorch_tutorial\logs")
writer.add_image("Resize",img_resize,0)
writer.add_image("Resize",tensor_img,1)
writer.close()
# tensorboard确实好用

In [16]:
# Compose - resize -2
trans_resize_2 = transforms.Resize(512)
# compose()参数需要是一个列表
# PIL -> PIL -> tensor
trans_compose = transforms.Compose([trans_resize_2,tensor_trans])
img_resize_2 = trans_compose(img)
writer = SummaryWriter(r"D:\PycharmProjects\xiaotudui_pytorch_tutorial\logs")
writer.add_image("Resize",img_resize_2,2)
writer.close()